fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: editorconfig-checker
        name: editorconfig-checker
        entry: uv run ec src/
        language: system
        pass_filenames: no

      - id: linters-ruff
        name: ruff
        entry: uv run ruff check ./src
        language: system
        pass_filenames: no
